name = "nil-blog"
description = "A robust, elegant dark theme, absed on after-dark"
license = "MIT"
homepage = "https://github.com/damienstanton/nil-blog"
min_version = "0.11.0"
demo = "https://damienstanton.com"

[extra]


[author]
name = "Damien Stanton"
homepage = "https://damienstanton.com"

[original]
name = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"
